debuerreotype/debuerreotype

- scripts/debuerreotype-slimify
Namely, the following policy edge case: (https://www.debian.org/doc/debian-policy/ch-docs.html#s-copyrightfile)
> /usr/share/doc/package may be a symbolic link to another directory in /usr/share/doc only if the two packages both come from the same source and the first package Depends on the second. These rules are important because copyright files must be extractable by mechanical means.
And the following in `dpkg(1)`: (https://manpages.debian.org/stretch/dpkg/dpkg.1.en.html)
> Note: the current implementation might re-include more directories and symlinks than needed, to be on the safe side and avoid possible unpack failures; future work might fix this.
See https://github.com/debuerreotype/docker-debian-artifacts/issues/10.
> Update slimify exclusion logic to match dpkg's internal behavior better

- build.sh
This is really some bizarre edge case in APT, but I haven't been able to reproduce it consistently with a smaller reproducer than fully re-building several Go packages (golang-github-jinzhu-inflection, then golang-gopkg-pg.v5 with --extra-package), so I don't feel like we even have enough information yet to bug the APT maintainers with it.
This simply removes the APT configuration from the "sbuild" variants which causes the bug to exhibit.
See also https://github.com/docker-library/postgres/pull/330 for another place where I've reproduced the same issue, but without `sbuild` involved at all (and ended up with a simple workaround there).
> Fix "sbuild --extra-package" usage

- build-all.sh
- build.sh
- scripts/.constants.sh
- scripts/debuerreotype-apt-get
- scripts/debuerreotype-chroot
- scripts/debuerreotype-fixup
- scripts/debuerreotype-gen-sources-list
- scripts/debuerreotype-init
- scripts/debuerreotype-minimizing-config
- scripts/debuerreotype-slimify
- scripts/debuerreotype-tar
- scripts/debuerreotype-version
This makes all our commands respond to `--help`, `-h`, `-?`, and `--version` consistently and cleanly.
> Refactor and normalize getopt for consistent UX

- build-all.sh
- build.sh
See https://github.com/debuerreotype/docker-debian-artifacts/issues/12#issuecomment-327192735.
The TL;DR is that it was great to apply `--merged-usr` to `stretch` while it was still `testing`, but now that it's `stable` and there are still `dpkg` bugs that aren't fixed, it doesn't make sense to apply in `stable`.  We'll revisit this when `buster` gets closer to release (hopefully with `dpkg` updates to make it moot, but I'm not holding my breath).
> Apply "--no-merged-usr" to all released suites in "build.sh"

- scripts/debuerreotype-init
- steamos.sh
```console
$ ls -lAFh output/steamos/amd64/*/rootfs.tar.xz
-rw-rw-r-- 1 tianon tianon 22M May 17  2017 output/steamos/amd64/alchemist_beta/rootfs.tar.xz
-rw-rw-r-- 1 tianon tianon 22M May 17  2017 output/steamos/amd64/alchemist/rootfs.tar.xz
-rw-rw-r-- 1 tianon tianon 30M Jan 24 17:31 output/steamos/amd64/brewmaster_beta/rootfs.tar.xz
-rw-rw-r-- 1 tianon tianon 30M Jan 22 14:32 output/steamos/amd64/brewmaster/rootfs.tar.xz
```
:tada:
> Improve "steamos.sh" to support all of {alchemist,brewmaster}{,_beta} properly

- .dockerignore
- Dockerfile
- build.sh
(Which also fixes `debuerreotype-version` to work properly inside the built image by including `VERSION` in the image.)
> Add "rootfs.debuerreotype-version" file to "build.sh" output

- scripts/debuerreotype-init
While trying to chase down a failure in Debian's `autopkgtest` I discovered this fun little edge case.
If I have `debuerreotype` create a directory locally, the permissions on that directory are `0755`, but if I use `mktemp -d`, they're `0700`, which gets embedded in the result of `debuerreotype-tar` as an entry for `./`, which causes the hash to change. :man_facepalming:
(Turns out the same is true of the ownership on that directory.)
> Fix "targetDir" permissions causing minor reproducibility issue

- scripts/.slimify-excludes
`<nthykier> tianon: the root of the issue is that "/usr/share/lintian/*" is excluded (breaking lintian).  The correct exclude would be "/usr/share/lintian/overrides/*"`
Thanks @nthykier :heart:
> Fix over-enthusiastic /usr/share/lintian excludes

- build.sh
- scripts/debuerreotype-init
This is important given that merged-usr may or may not be enabled for us by default at the debootstrap layer in the future (this also fixes a bug in "build.sh" where we incorrectly detected "stable" suites).
> Properly apply --merged-usr / --no-merged-usr

- scripts/.slimify-excludes
- scripts/.slimify-includes
- scripts/debuerreotype-slimify
See https://anonscm.debian.org/cgit/collab-maint/localepurge.git/tree/usr/share/localepurge/gen-dpkg-cfg.pl?id=b32c8d46d43be2027096f5a202ac789a637ceb39#n9
Once again, thanks @nthykier! :heart:
Here's an example `diffoscope` of this change in the current tarballs: (including both #32 and #34 as well, since that's what I've got tarballs for handy for diffing against)
```diff
|#######################################################################################################################################################################################|  100%                             Time: 0:00:05 
--- rootfs.tar.xz
+++ output/20180426/amd64/stretch/slim/rootfs.tar.xz
├── rootfs.tar
│ ├── file list
│ │ @@ -120,15 +120,15 @@
│ │  -rw-r--r--   0        0        0      657 2017-03-22 …
```
> Update slimify with more excludes and more includes from src:localepurge

- .travis.yml
Squignix is necessary for building etch and woody who otherwise are so poorly behaved they get rate limited by snapshot.d.o (https://travis-ci.org/debuerreotype/debuerreotype/builds/479633791).
This should fix the failing builds. :crossed_fingers:
> Add "hack-my-builds" to Travis

- build.sh
- scripts/.tar-exclude
- more aggressive keyring handling (buster's got wheezy's key relegated to the removed-keys keyring now, for example)
- exclude "/run/shm/.run-transition" (which only shows up when building with buster+ debootstrap, for some reason -- possibly related to ischroot/mount differences?)
> Tweak a bit to ensure we're still good when updating our Dockerfile to be FROM buster (newer debootstrap)

- build.sh
Fixes minor regression in #55 (`rootfs.manifest` files were completely empty, which is obviously pretty useless).
Discovered at https://github.com/docker-library/official-images/pull/5486#issuecomment-468472624 (thanks @yosifkit). :+1:
> Fix manifest file generation

- .travis.yml
- build.sh
- scripts/.fix-apt-comments.sh
- scripts/.gpgv-ignore-expiration.sh
- scripts/debuerreotype-gpgv-ignore-expiration-config
- scripts/debuerreotype-minimizing-config
For the sake of EOL releases (whose archive keys have often expired), we need a fake `gpgv` substitute that will essentially ignore *just* key expiration.
(So we get *some* signature validation instead of using something like `--allow-unauthenticated` or `--force-yes` which disable security entirely instead.)
This workaround *only* gets applied when we're doing an EOL build, and only when the APT version is new enough to need it (older APT versions didn't verify that).
This is the last bits needed in `debuerreotype` itself to finally take care of https://github.com/debuerreotype/docker-debian-artifacts/issues/65.  With this, I have successfully verified the full reproducibility of `woody`/3.0 through `wheezy`/7.0 across two days across `i386`, `arm`, `armel`, `armhf`, and `amd64` as …
> Add workaround for EOL suites with expired GPG keys

- build.sh
- scripts/.tar-exclude
- scripts/debuerreotype-tar
See https://salsa.debian.org/apt-team/apt/commit/5555ef9850b7e66aa02d39bb7d624fdf3e43edb2 (APT 0.9.14 removed the final bit of support for `/var/state/apt`).
This also moves the Potato-specific additional exclusions into `build.sh` so that they only get applied to Potato.
> Also exclude "/var/state/apt" appropriately for old APT versions

- .travis.yml
This doesn't help us test `riscv64` (#70), but it does seem prudent regardless given Trusty's age and impending EOL.
> Update Travis to use Bionic instead of Trusty

- scripts/debuerreotype-init
Sometimes, it's practical to skip all signature checks, e.g. when
building from a Debian ISO image which doesn't contain a signed Release
file.
Add the `--no-check-gpg` and `--check-gpg` flags, the latter is set per
default.
Fixes #73
> Allow skipping GPG signature checks

- .github/workflows/ci.yml
ubuntu-20.04 and not ubuntu-latest is at the moment needed for riscv64 / qemu-user-static support
> re-enabel ARCH riscv64 and change runs-on to ubuntu-20.04

- build.sh
We include the `-removed` keyring for the normal archive, and we need to do the same for ports (for the same reasons).
> Include the "-removed" keyring for ports too

- scripts/.slimify-excludes
- scripts/.slimify-includes
These come from reviewing the following localepurge diff:
https://salsa.debian.org/elmig-guest/localepurge/-/compare/9899763213226f293a29c0ebd2be2e45aace01ee...2608425c05b75c9c65d04ba12f099eb9eab51e35?w=1#dc5bce24f8152e7a979333f0ad4e46acae10e6c6
(Ignoring bits we had ignored previously, like vim files, and now sorting the lines case insensitively so they're easier to maintain/review.)
We should probably re-review the ones we've skipped and add some note here as to why we've done so, and we should probably expand all the `localepurge` references to `@LOCALE@` to both `C` and `C.UTF-8` so that those two generic locales remain usable in "slimified" images.
> Add new slimify bits from localepurge 0.7.3.9

- examples/debian.sh
With this we can build a rootfs completely customized for the targetted
needs.
For example do we really need e2fstools in a container? By using
--exclude="e2fstools" we don't include it even though its deemed
essential for debian.
Signed-off-by: BlackEagle <ike.devolder@gmail.com>
> allow building with includes and excludes

- examples/debian.sh
For historical reasons (related to their usefulness in debugging non-working container networking in container early days before `--network container:xxx`), Debian 10 and older non-slim images included both `ping` and `ip` above `minbase`, but in 11+ (Bullseye), that will no longer be the case and we will instead be a faithful minbase again 😄
> Remove "ping" and "ip" from Debian 11+

- .docker-image.sh
- docker-run.sh
- examples/debian-all.sh
- examples/debian.sh
- examples/raspbian.sh
- examples/steamos.sh
- examples/ubuntu.sh
- scripts/.apt-version.sh
- scripts/.constants.sh
- scripts/.debian-mirror.sh
- scripts/.dpkg-arch.sh
- scripts/.fix-apt-comments.sh
- scripts/.snapshot-url.sh
- scripts/debuerreotype-apt-get
- scripts/debuerreotype-chroot
- scripts/debuerreotype-debian-sources-list
- scripts/debuerreotype-fixup
- scripts/debuerreotype-gpgv-ignore-expiration-config
- scripts/debuerreotype-init
- scripts/debuerreotype-minimizing-config
- scripts/debuerreotype-slimify
- scripts/debuerreotype-tar
- scripts/debuerreotype-version
If any of these ever fails, they won't print an error without `-v` (and many of them are used as sanity checks, so this is both useful and important).
> Add "-v" to all "readlink" invocations

- README.md
- examples/raspbian.sh
- examples/steamos.sh
- examples/ubuntu.sh
- scripts/debuerreotype-init
- scripts/debuerreotype-recalculate-epoch
This allows (for example) `examples/ubuntu.sh` to finally populate `/etc/apt/sources.list` appropriately.
> Add new "debuerreotype-recalculate-epoch" script for non-Debian chroots

- scripts/debuerreotype-slimify
Closes #10
I don't love this, but it doesn't look like this is getting fixed in `update-alternatives` any time soon, so we'll just special case it instead.
Relevant `diffoscope`:
```diff
--- old/20210721/amd64/bullseye/slim/rootfs.tar.xz
+++ new/20210721/amd64/bullseye/slim/rootfs.tar.xz
├── rootfs.tar
│ ├── file list
│ │ @@ -2286,14 +2286,19 @@
│ │  drwxr-xr-x   0        0        0        0 2021-07-21 00:00:00.000000 usr/share/lintian/
│ │  drwxr-xr-x   0        0        0        0 2021-07-21 00:00:00.000000 usr/share/lintian/overrides/
│ │  drwxr-xr-x   0        0        0        0 2021-04-13 22:43:39.000000 usr/share/lintian/profiles/
│ │  drwxr-xr-x   0        0        0        0 2021-07-21 00:00:00.000000 usr/share/lintian/profiles/dpkg/
│ │  -rw-r--r--   0        0        0      270 …
```
> Explicitly keep /usr/share/man/man[0-9]/ in slim variants

- scripts/debuerreotype-init
This is similar to what happens in `debuerreotype-chroot`, but for `debootstrap` too, since sometimes the scripts for the initial packages can leave dangling mounts (most notably `/run/shm` in wheezy).
> Invoke "debootstrap" inside "unshare --mount" by default

- examples/debian-all.sh
- examples/debian.sh
- examples/oci-image.sh
- examples/raspbian.sh
- examples/steamos.sh
- examples/ubuntu.sh
There are other reasonable ways to create these that don't involve using such low level tooling (https://github.com/tianon/debian-bin/blob/7d6951fa33b8cf104f91f08afa3767343cfb4476/docker-sbuild/docker-image-to-sbuild-schroot), and thus have a lot more flexibility.
Closes #115
Refs #68
> Remove sbuild variants

- .github/workflows/ci.yml
- .validate-ubuntu.sh
This should help avoid "oops" moments like a4582efca5301591bb59f9766ca15a98a0582090 (which happens repeatedly).
Closes #119
> Add a test to validate no-https snapshot usage

- examples/debian-all.sh
- examples/debian.sh
The usage of `qemu-debootstrap` is deprecated in favor of binfmt's "fix-binary" mode (where the QEMU binaries don't have to be copied into the resulting chroot).
> Remove explicit (deprecated) "--qemu" flag

- Dockerfile
- examples/debian.sh
- examples/raspbian.sh
- examples/steamos.sh
- examples/ubuntu.sh
- scripts/.apt-version.sh
- scripts/.debootstrap-scripts/potato
- scripts/.debootstrap-scripts/slink
- scripts/.dpkg-arch.sh
- scripts/debuerreotype-chroot
- scripts/debuerreotype-init
- scripts/debuerreotype-minimizing-config
- scripts/debuerreotype-slimify
This depends on https://salsa.debian.org/installer-team/debootstrap/-/merge_requests/63 (which is included in our `Dockerfile` here) and likely requires running on an actual 32bit system (otherwise it'll fail with inode-too-large issues on either the target rootfs or even in reading files from `/proc` if your target rootfs is 32bit; see https://github.com/moby/moby/issues/5364#issuecomment-480312843).
> Add Slink support (and various other minor tweaks)

- .github/workflows/ci.yml
```console
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://snapshot.debian.org/archive/debian-ports/20210301T000000Z unstable InRelease: The following signatures were invalid: EXPKEYSIG 5A88D659DCB811BB Debian Ports Archive Automatic Signing Key (2021) <ftpmaster@ports-master.debian.org>
W: GPG error: http://snapshot.debian.org/archive/debian-ports/20210301T000000Z unreleased InRelease: The following signatures were invalid: EXPKEYSIG 5A88D659DCB811BB Debian Ports Archive Automatic Signing Key (2021) <ftpmaster@ports-master.debian.org>
E: The repository 'http://snapshot.debian.org/archive/debian-ports/20210301T000000Z unreleased InRelease' is not signed.
```
> Update CI debian-ports timestamps (for ports key expiration)

- .github/workflows/ci.yml
- Dockerfile
- README.md
- examples/debian.sh
- scripts/debuerreotype-fixup
- scripts/debuerreotype-init
See also https://www.freedesktop.org/software/systemd/man/machine-id.html for more detail.
```diff
$ diffoscope validate.bak/20220201/riscv64/unstable/rootfs.tar.xz validate/20220201/riscv64/unstable/rootfs.tar.xz
--- validate.bak/20220201/riscv64/unstable/rootfs.tar.xz
+++ validate/20220201/riscv64/unstable/rootfs.tar.xz
├── rootfs.tar
│ ├── file list
│ │ @@ -166,15 +166,14 @@
│ │  -rw-r--r--   0        0        0      191 2021-10-09 09:45:31.000000 etc/libaudit.conf
│ │  lrwxrwxrwx   0        0        0        0 2022-02-01 00:00:00.000000 etc/localtime -> /usr/share/zoneinfo/Etc/UTC
│ │  -rw-r--r--   0        0        0    11876 2022-01-31 09:33:28.000000 etc/login.defs
│ │  drwxr-xr-x   0        0        0        0 2022-02-01 00:00:00.000000 etc/logrotate.d/
│ │  -rw-r--r--   0 …
```
> Adjust "fixup" to empty machine-id and "examples/debian.sh" to exclude it entirely

- .github/workflows/ci.yml
- examples/debian.sh
- scripts/debuerreotype-debian-sources-list
The intention is to start with *just* unstable for a month or two, but the goal is to include this in bookworm+ (so it will hit testing images eventually).
See https://lists.debian.org/debian-devel/2021/11/msg00026.html for some discussion around this.
cc @julian-klode
Here's an example of forcing the generation for `bookworm`:
```yaml
Types: deb
URIs: http://deb.debian.org/debian
Suites: bookworm
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
Types: deb
URIs: http://security.debian.org/debian-security
Suites: bookworm-security
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
Types: deb
URIs: http://deb.debian.org/debian
Suites: bookworm-updates
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
```
(The …
> Add initial stab at deb822-style sources.list

- examples/debian.sh
- examples/raspbian.sh
- examples/steamos.sh
- examples/ubuntu.sh
This becomes useful for identifying changes in debootstrap that cause reproducibility issues (such as the recent `usr-is-merged` changes; https://github.com/debuerreotype/docker-debian-artifacts/issues/174 / https://salsa.debian.org/installer-team/debootstrap/-/merge_requests/71 / https://salsa.debian.org/installer-team/debootstrap/-/merge_requests/72).
Closes #138
> Add "rootfs.debootstrap-version" as another output file

- docker-run.sh
- scripts/debuerreotype-chroot
Hi.
While updating my base images, I tend to build a lot of images and hack `APT_PROXY` into debuerreotype to make use of apt-cacher-ng. So, here's a patch for that.
I also noticed that setting `DEBIAN_FRONTEND=noninteractive` in a script does nothing because inside of `debuerreotype-chroot` we clear the environment and don't forward that. This makes `debuerreotype-apt-get install` fail on packages that want to be configured, e.g. `console-setup`.
> Make DEBIAN_FRONTEND useable and support apt-cacher

- Dockerfile
```markdown
distro-info-data (0.56) unstable; urgency=medium
[ Stefano Rivera ]
* Add Debian 14 "forky" with a vague creation date.
[ Brian Murray ]
* Correct Update 23.04 release date to 2023-04-20
-- Benjamin Drung <bdrung@debian.org>  Mon, 31 Oct 2022 14:51:00 +0100
distro-info-data (0.55) unstable; urgency=medium
[ Stefano Rivera ]
* Mark python3 Build-Depend as <!nocheck>.
[ Thomas Bechtold ]
* Add dates for Ubuntu 23.04, Lunar Lobster (LP: #1993667)
-- Benjamin Drung <bdrung@debian.org>  Fri, 28 Oct 2022 11:09:05 +0200
distro-info-data (0.54) unstable; urgency=medium
* Update Debian ELTS dates to ~10 years of support (Closes: #1014837)
* Correct release date of Debian 8 (jessie) to 2015-04-26
* Restrict maximum line length to 79 characters
* Fix all pylint complaints (except …
```
> Update distro-info-data to 0.56

- examples/oci-image.sh
This drops the fallback behaviors that we shouldn't need anymore, allows us to generate our OCI contents to a directory instead of a tarball, and updates our `blobs/sha256/xxx` entries to instead be symlinks to files with better names under `blobs/` (`blobs/image-manifest.json`, etc).
```console
$ find -ls
42995983      4 drwxrwxr-x   3 tianon   tianon       4096 Oct  2 17:00 .
42995984      4 drwxrwxr-x   3 tianon   tianon       4096 Oct  2 17:00 ./blobs
42995989      4 drwxrwxr-x   2 tianon   tianon       4096 Oct  2 17:00 ./blobs/sha256
42996020      0 lrwxrwxrwx   1 tianon   tianon         16 Oct  2 17:00 ./blobs/sha256/0449b3622c2481758a471eb896afc4f61395ce504b442bc06630f1a16792c54f -> ../rootfs.tar.gz
42996007      0 lrwxrwxrwx   1 tianon   tianon         22 Oct  2 17:00 …
```
> Update "oci-image.sh" to allow directory output

- .github/workflows/ci.yml
- examples/debian.sh
This is the inevitable follow-up to https://github.com/debuerreotype/debuerreotype/pull/128
@julian-klode I'd love to hear your thoughts on whether you think we're ready to go to this next stage? :bow:
(I haven't heard of much bad breakage, but I imagine you're closer to where those might occur than I am :sweat_smile:)
> Update to deb822-sources for bookworm (previously sid-only)

- examples/oci-image.sh
In the OCI image specification, a base64 representation of the actual data blob can be embedded inside any content descriptor (within reasonable size limits; https://github.com/opencontainers/image-spec/pull/826, https://github.com/opencontainers/distribution-spec/pull/293).  Since our "config" and "image manifest" objects are both relatively small, we can use this to help reduce the ncessary round-trips while consuming these images.
> Add embedded "data" fields to generated OCI images

- .github/workflows/ci.yml
(This should remove the Node.js deprecation warnings in our CI builds)
> Update to actions/checkout@v3

- scripts/debuerreotype-minimizing-config
Aptitude's manual link was not working, changed to https://www.debian.org/doc/manuals/aptitude/
> docs: fix link for aptitude manual

- .github/workflows/ci.yml
- .gitmodules
- .validate-dockerfile.sh
- .validate-readme.sh
- Dockerfile
- README.md
- generate-github-actions.sh
This also stores the verbatim artifacts so that monitoring change-over-time is easier like all our other validation now has:
https://github.com/debuerreotype/validation-artifacts/compare/f89e6a3db51bc0f367bbef74f17001f5e508e96a..bbc7e73f82b41312ceb4a5c5810eadbf8b8aee73
> Update hard-coded checksums in `Dockerfile` and `README.md`, and add CI to validate them

- .validate-dockerfile.sh
- examples/debian.sh
- https://bugs.debian.org/764204 "apt-cache calls fcntl() on 65536 FDs"
- https://bugs.launchpad.net/bugs/1332440 "apt-get update very slow when ulimit -n is big"
> Add `ulimit` workarounds when building Jessie
